spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Carros
    username: root
    password: 995410
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
